### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/data/VOC/VOC2007/JPEGImages/000006.jpg'

### ISSUE THREAD

**Issue by Sunny20236** [CSIPlab/EBAD#3]
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "attack_bb_det.py", line 502, in <module>
    main()
  File "attack_bb_det.py", line 265, in main
    im_np = np.array(Image.open(im_path).convert('RGB'))
  File "/data/songsl/anaconda/envs/EBAD/lib/python3.8/site-packages/PIL/Image.py", line 3218, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/data/VOC/VOC2007/JPEGImages/000006.jpg'

please help me， please

**Comment by Sunny20236** [comment]
I have downloaded the full dataset

**Comment by Sunny20236** [comment]
Changing the data_root on line 249 of the attack_bb_det.py file to an absolute path resolves the problem!
